# <font color='#2F4F4F'>AfterWork Data Science: Recurrent Neural Networks with Python - Project</font>

## <font color='#2F4F4F'>Step 1. Business Understanding </font>

### a) Specifying the Research Question

Build a recurrent neural networks model that will be used to predict Tesla stock prices in 2017 using data from 2012-2016

### b) Defining the Metric for Success

Build a neural networks regression model with an RSME  less than 10% of the target mean.

### c) Understanding the Context 

Stockpy is an innovative fintech enabling financial prosperity for the entire population. It is a venture funded startup based in Palo Alto bringing world-class financial experiences to a continually growing customer base. As Stockpy enters an expansion phase for innovative fintech product offerings, it aims to enhance the enormous value in data processing and analysis for continuous growth and success.

As a Finance Data Scientist for Stockpy, you provide leadership to turn cutting-edge technology into actionable insights; unlocking the power of data that provides value to business decisions and customer service enhancements.

### d) Recording the Experimental Design

* Business Understanding
* Data Exploration
* Data Preparation
* Data Modeling and Evaluation
* Summary of Findings and Recommendation
* Challenging the Solution

## <font color='#2F4F4F'>Step 2. Data Importation</font>

In [1]:
# Importing standard libraries
# ---
# 
import pandas as pd
import numpy as np

In [2]:
# Importing our dataset
# ---
#
df_train = pd.read_csv('https://bit.ly/38dSbSb')
df_train

,Date,Open,High,Low,Close,Adj Close,Volume
0,2012-01-03,5.788000,5.900000,5.530000,5.616000,5.616000,4640500
1,2012-01-04,5.642000,5.734000,5.500000,5.542000,5.542000,3150500
2,2012-01-05,5.552000,5.586000,5.370000,5.424000,5.424000,5027500
3,2012-01-06,5.440000,5.558000,5.282000,5.382000,5.382000,4931500
4,2012-01-09,5.400000,5.498000,5.224000,5.450000,5.450000,4485000
...,...,...,...,...,...,...,...
1253,2016-12-23,41.599998,42.689999,41.542000,42.667999,42.667999,23352500
1254,2016-12-27,42.976002,44.450001,42.883999,43.905998,43.905998,29578500
1255,2016-12-28,44.306000,44.759998,43.439999,43.948002,43.948002,18912500
1256,2016-12-29,43.712002,43.840000,42.824001,42.936001,42.936001,20225000
1257,2016-12-30,43.259998,43.500000,42.335999,42.737999,42.737999,23213000

## <font color='#2F4F4F'>Step 3. Data Exploration</font>

In [3]:
# Sample dataset
# ---
#
df_train.sample(3)

            Date    Open       High        Low      Close  Adj Close    Volume
24    2012-02-07   6.360   6.360000   6.164000   6.320000   6.320000   5108000
1255  2016-12-28  44.306  44.759998  43.439999  43.948002  43.948002  18912500
143   2012-07-27   5.742   5.932000   5.620000   5.902000   5.902000   8365000

In [4]:
# Statistical summary
# ---
#
df_train.describe()

,Open,High,Low,Close,Adj Close,Volume
count,1258.000000,1258.000000,1258.000000,1258.000000,1258.000000,1.258000e+03
mean,31.997898,32.558671,31.403696,31.989245,31.989245,2.551310e+07
std,16.911515,17.148543,16.649245,16.903500,16.903500,2.259037e+07
min,5.324000,5.370000,4.528000,4.558000,4.558000,1.824500e+06
25%,8.403000,8.556000,8.197000,8.379500,8.379500,1.059400e+07
50%,39.411000,40.123998,38.709000,39.427000,39.427000,2.007650e+07
75%,45.214499,45.934999,44.303000,45.076502,45.076502,3.245150e+07
max,57.534000,58.284000,56.080002,57.208000,57.208000,1.858195e+08

## <font color='#2F4F4F'>Step 4. Data Preparation</font>

In [ ]:
# Getting our train dataset
# ---
#
train_set = df_train.iloc[:, 1:2].values
print(train_set)

In [ ]:
# Performing Feature scaling
# ---
#
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0,1))
training_set_scaled = sc.fit_transform(train_set)

In [ ]:
# Creating a dataset with 60 timesteps and 1 output
# ---
#
X_train = []
y_train = []
for i in range(60, 1258):
    X_train.append(training_set_scaled [i-60:i, 0])
    y_train.append(training_set_scaled [i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)
X_train, y_train

In [ ]:
# Reshaping 
# ---
#
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

##  <font color='#2F4F4F'>Step 5. Data Modeling</font>

In [9]:
# Building the RNN
# import keras

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [10]:
# Initialising the RNN

regressor = Sequential()

# Adding the first LSTM layer and some Dropout regularisation

regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (X_train.shape[1], 1)))
regressor.add(Dropout(0.2))

# Adding a second LSTM layer and some Dropout regularisation

regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

# Adding a third LSTM layer and some Dropout regularisation

regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

# Adding a fourth LSTM layer and some Dropout regularisation

regressor.add(LSTM(units = 50, return_sequences = False))
regressor.add(Dropout(0.2))

# Adding the output layer

regressor.add(Dense(units = 1))

In [11]:
# Compile the RNN 
# ---
#

regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [12]:
# Fitting the RNN to the training set
# ---
#
regressor.fit(X_train, y_train, epochs = 100, batch_size = 32)

Epoch 1/100
38/38 [==============================] - 14s 27ms/step - loss: 0.0632
Epoch 2/100
38/38 [==============================] - 1s 21ms/step - loss: 0.0108
Epoch 3/100
38/38 [==============================] - 1s 22ms/step - loss: 0.0086
Epoch 4/100
38/38 [==============================] - 1s 23ms/step - loss: 0.0085
Epoch 5/100
38/38 [==============================] - 1s 22ms/step - loss: 0.0081
Epoch 6/100
38/38 [==============================] - 1s 30ms/step - loss: 0.0081
Epoch 7/100
38/38 [==============================] - 1s 27ms/step - loss: 0.0067
Epoch 8/100
38/38 [==============================] - 1s 22ms/step - loss: 0.0064
Epoch 9/100
38/38 [==============================] - 1s 21ms/step - loss: 0.0056
Epoch 10/100
38/38 [==============================] - 1s 22ms/step - loss: 0.0058
Epoch 11/100
38/38 [==============================] - 1s 26ms/step - loss: 0.0063
Epoch 12/100
38/38 [==============================] - 1s 24ms/step - loss: 0.0063
Epoch 13/100
38/38 [==============================] - 1s 26ms/step - loss: 0.0056
Epoch 14/100
38/38 [==============================] - 1s 19ms/step - loss: 0.0052
Epoch 15/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0051
Epoch 16/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0051
Epoch 17/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0053
Epoch 18/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0052
Epoch 19/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0049
Epoch 20/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0046
Epoch 21/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0051
Epoch 22/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0051
Epoch 23/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0043
Epoch 24/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0050
Epoch 25/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0047
Epoch 26/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0050
Epoch 27/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0041
Epoch 28/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0044
Epoch 29/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0041
Epoch 30/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0039
Epoch 31/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0044
Epoch 32/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0040
Epoch 33/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0037
Epoch 34/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0035
Epoch 35/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0044
Epoch 36/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0036
Epoch 37/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0038
Epoch 38/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0037
Epoch 39/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0033
Epoch 40/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0034
Epoch 41/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0035
Epoch 42/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0036
Epoch 43/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0032
Epoch 44/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0034
Epoch 45/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0038
Epoch 46/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0032
Epoch 47/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0031
Epoch 48/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0032
Epoch 49/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0031
Epoch 50/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0035
Epoch 51/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0029
Epoch 52/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0033
Epoch 53/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0032
Epoch 54/100
38/38 [==============================] - 0s 13ms/step - loss: 0.0033
Epoch 55/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0030
Epoch 56/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0030
Epoch 57/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0032
Epoch 58/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0030
Epoch 59/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0026
Epoch 60/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0027
Epoch 61/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0029
Epoch 62/100
38/38 [==============================] - 0s 13ms/step - loss: 0.0029
Epoch 63/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0026
Epoch 64/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0029
Epoch 65/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0030
Epoch 66/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0029
Epoch 67/100
38/38 [==============================] - 1s 15ms/step - loss: 0.0024
Epoch 68/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0028
Epoch 69/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0026
Epoch 70/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0023
Epoch 71/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0026
Epoch 72/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0024
Epoch 73/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0025
Epoch 74/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0027
Epoch 75/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0023
Epoch 76/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0023
Epoch 77/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0024
Epoch 78/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0023
Epoch 79/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0023
Epoch 80/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0021
Epoch 81/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0024
Epoch 82/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0023
Epoch 83/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0020
Epoch 84/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0021
Epoch 85/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0021
Epoch 86/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0021
Epoch 87/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0022
Epoch 88/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0021
Epoch 89/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0022
Epoch 90/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0020
Epoch 91/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0021
Epoch 92/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0020
Epoch 93/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0020
Epoch 94/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0019
Epoch 95/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0021
Epoch 96/100
38/38 [==============================] - 1s 15ms/step - loss: 0.0020
Epoch 97/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0021
Epoch 98/100
38/38 [==============================] - 1s 14ms/step - loss: 0.0020
Epoch 99/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0021
Epoch 100/100
38/38 [==============================] - 1s 13ms/step - loss: 0.0020

In [13]:
# Making predictions: Getting the predicted stock price for 2017
# ---
df_test=pd.read_csv("/content/TSLA.csv")
df_test.head(20)

FileNotFoundError: ignored

In [ ]:
real_price = df_test.iloc[:, 1:2].values

# Getting the Predicted Stock Price of 2017

#
dataset = pd.concat((df_train['Open'],
                           df_test['Open']), axis=0)

#
inputs = dataset[len(dataset)-len(df_test)-60:].values

# Reshaping the inputs to have only 1 column
# ---
#
inputs = inputs.reshape(-1, 1)


# Using the scale set by the training set to scale the test inputs
# ---
#
inputs = sc.transform(inputs)

# Then creating the test data structure just as we did for the train dataset
# ---

X_test = []
y_test = []

for i in range(60, len(inputs)):
    X_test.append(inputs[i-60:i, 0])
    y_test.append(inputs[i, 0])

X_test, y_test  = np.array(X_test), np.array(y_test)  
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

# Making our Predictions
# ---
#
predicted_price = regressor.predict(X_test)


predicted_price = sc.inverse_transform(predicted_price)
print(predicted_price)

In [ ]:
# Visualizing the results
import matplotlib.pyplot as plt 

plt.plot(real_price, color='red', label='Real Google Stock Price')
plt.plot(predicted_price, color='blue',
         label='Predicted Google Stock Price')
plt.title('Google Stock Price Prediction by TDP')
plt.xlabel('Time')
plt.ylabel('Google Stock Price')
plt.legend()
plt.show()

In [ ]:
# Model Evaluation
import math
from sklearn.metrics import mean_squared_error
rmse = math.sqrt(mean_squared_error(real_price, predicted_price))
print(rmse)
print(real_price.mean())

## <font color='#2F4F4F'>Step 6. Summary of Findings and Recommendation</font>

Your observation goes here...

* The RMSE value obtained is 3.5 which less than 10% of the target mean (62.85). This means the model is of high performance


*  The visualization on real and predicted values shows a similar pattern, indicating a high model accuracy

## <font color='#2F4F4F'>Step 7. Challenging our Solution</font>

a) Did we have the right question?

Yes

b) Did we have the right data?

Yes, the data we had was sufficient in answering the research question

c) What can be done to improve the solution?


The model performance can be improved through:


*   Training with more data

*   Adding more LSTM layers

*  Increasing the timesteps

*  Adding some other indicators

*  Adding more neurons in the LSTM layers